# Generated by Django 5.0.1 on 2024-02-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0003_alter_buyer_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='area',
            field=models.CharField(choices=[('W', 'Windsor'), ('LS', 'LaSalle'), ('A', 'Amherstburg'), ('L', 'Lakeshore'), ('LE', 'Leamington'), ('C', 'Chatham'), ('T', 'Toronto'), ('WA', 'Waterloo')], default='C', max_length=2),
        ),
    ]
