# Generated by Django 5.0.1 on 2024-02-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0004_alter_buyer_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='car_price',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
    ]
