# Generated by Django 5.0.2 on 2024-03-07 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0014_alter_ordervehicle_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartype',
            name='image',
            field=models.ImageField(null=True, upload_to='cartype_images/'),
        ),
    ]
